### ISSUE TITLE
5-7中的cin.get()

### ISSUE THREAD

**Issue by wenheyuran** [PytLab/Cpp-Primer-Plus#1]
哈喽，前辈你好！最近学习C++时，做的5-7，一开始没有加for前和for最后的cin.get()，之后就一直不正常，producer会直接跳过，到year上。加了之后才正常。所以想请教一下，为什么要加cin.get()呢？

**Comment by PytLab** [comment]
`std::cin.get()`是为了去掉缓冲区中的换行符的`\n`，当你第一次输入的时候缓冲区中最后会有一个换行符，最初使用`cin`读取的时候他并不会读取缓冲区的换行符，如果没有`cin.get()`将其读取出来，当再次遇到`cin >> ch`的时候，程序并不会停止，因为缓冲区中还有个换行符，他就会把他读出来然后继续执行了。

**Comment by plxdhong** [comment]
我已收到你的邮件，这个问题我会研究一下，最近工作繁重，不能及时回复。😉我是你晚辈啦~



发自我的小米手机
在 wenheyuran <notifications@github.com>，2017年10月30日 21:39写道：

哈喽，前辈你好！最近学习C++时，做的5-7，一开始没有加for前和for最后的cin.get()，之后就一直不正常，producer会直接跳过，到year上。加了之后才正常。所以想请教一下，为什么要加cin.get()呢？
